import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import WhatsAppFAB from "@/components/WhatsAppFAB";
import ThemeToggle from "@/components/ThemeToggle";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Jospeh Kakkassery Poertfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-base-100 text-base-content">
        <Navbar />
        <ThemeToggle />
        <WhatsAppFAB />

        {children}
        
        <Footer />
        
      </body>
    </html>
  );
}
